### ISSUE TITLE
service is None

### ISSUE THREAD

**Issue by fredfanatics** [davidedelpapa/gphotospy#12]
I get the following error:

`TypeError                                 Traceback (most recent call last)
<ipython-input-45-655c8af756db> in <module>
     10 print(service)
     11 # Init the album manager
---> 12 album_manager = Album(service)
     13 
     14 # Create a new album

~/jupyter/lib/python3.7/site-packages/gphotospy/album.py in __init__(self, service)
    170         """
    171 
--> 172         self._service = service["service"]
    173         self._secrets = service["secrets"]
    174 

TypeError: 'NoneType' object is not subscriptable`

**Comment by headphonejames** [comment]
same.

**Comment by cschimke1** [comment]
I am having this problem as well.

**Comment by durip** [comment]
same for me ..., but I figured it out
Its because google-api-python-client version 2.x. 
davidedelpapa please migrate gphotospy to this version (https://github.com/googleapis/google-api-python-client/blob/master/UPGRADING.md)

temporary solution:
sudo python3 -m pip install 'google-api-python-client==1.12.8' --force-reinstall

**Comment by davidedelpapa** [comment]
Closed as the latest version (0.2.0) gets on par with Google API 2.0.0. Thank you all for contributing to this.
